name: Maven Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'adopt'

    - name: Build com Maven
      run: mvn -B package --file pom.xml

    - name: Criando o diretório para o Build do JAR
      run: mkdir ./jar-upload

    - name: Copy JAR to Separate Directory
      run: cp ./target/*.jar ./jar-upload

      
    - name: Enviando os JAR por FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./jar-upload/
        server-dir: ~/appservers/standalone/

    - name: Install SSH Client
      run: sudo apt-get install openssh-client sshpass expect


    - name: Teste de conexão SSH
      env:
        SSH_USER_PASSWORD: ${{ secrets.SSH_USER_PASSWORD }}
        SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      run: |
        expect -c "
        set timeout 20
        spawn ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_ADDRESS
        expect \"password:\"
        send \"$SSH_USER_PASSWORD\r\"
        expect \"$ \"
        send \"ls -l\r\"
        expect \"$ \"
        send \"exit\r\"
        expect eof
        "


        
