name: Maven Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Directory for JAR
      run: mkdir ./jar-upload

    - name: Copy JAR to Separate Directory
      run: cp ./target/*.jar ./jar-upload

      
    - name: Upload to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./jar-upload/
        server-dir: ~/appservers/standalone/

    - name: Install SSH Client
      run: sudo apt-get install openssh-client sshpass

    - name: Setup SSH Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan integrator.host >> ~/.ssh/known_hosts

    - name: Execute Script via SSH
      env:
        SSH_KEY_PASSPHRASE: ${{ secrets.REMOTE_SSH_KEY_PASS }}
        SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
      run: sshpass -p $REMOTE_SSH_KEY_PASS ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_ADDRESS 'bash -s' <     ~/appservers/tmp/IntegratorExemploDeployGit-0.0.1-SNAPSHOT.sh stop
