name: Maven Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_ADDRESS }} >> ~/.ssh/known_hosts

    - name: Transfer JAR to Server via Rsync
      env:
        SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }} # Adicione essa linha
        DEPLOY_PATH: ~/appservers/standalone/
      run: |
        rsync -avz -e "ssh -i ~/.ssh/id_rsa" --progress ./target/*.jar $SERVER_USERNAME@$SERVER_ADDRESS:$DEPLOY_PATH
